#
# Base image with defaults for all stages
FROM registry.access.redhat.com/ubi9-minimal@sha256:e12131db2e2b6572613589a94b7f615d4ac89d94f859dad05908aeb478fb090f AS base
COPY --from=ghcr.io/astral-sh/uv:0.7.17@sha256:68a26194ea8da0dbb014e8ae1d8ab08a469ee3ba0f4e2ac07b8bb66c0f8185c1 /uv /bin/uv

COPY LICENSE /licenses/

ENV APP_ROOT=/opt/app-root
ENV \
    # use venv from ubi image
    UV_PROJECT_ENVIRONMENT=${APP_ROOT} \
    # compile bytecode for faster startup
    UV_COMPILE_BYTECODE="true" \
    # disable uv cache. it doesn't make sense in a container
    UV_NO_CACHE=true \
    BASH_ENV="${APP_ROOT}/bin/activate" \
    ENV="${APP_ROOT}/bin/activate" \
    PROMPT_COMMAND=". ${APP_ROOT}/bin/activate"

# Install base dependencies
RUN microdnf install -y python3.12 make findutils && microdnf clean all
WORKDIR ${APP_ROOT}/src


#
# Builder image
#
FROM registry.access.redhat.com/ubi9/python-312@sha256:2049a086cccdabf5608cbdc9cd022f3e54d2344f7e11dc156f6f3fa0f5a3c9b6 AS builder
COPY --from=ghcr.io/astral-sh/uv:0.7.17@sha256:68a26194ea8da0dbb014e8ae1d8ab08a469ee3ba0f4e2ac07b8bb66c0f8185c1 /uv /bin/uv

ENV \
    # use venv from ubi image
    UV_PROJECT_ENVIRONMENT=${APP_ROOT} \
    # compile bytecode for faster startup
    UV_COMPILE_BYTECODE="true" \
    # disable uv cache. it doesn't make sense in a container
    UV_NO_CACHE=true

# I don't want to mess with permission issues in the builder image. We use a non-root user in the final images
USER 0

COPY pyproject.toml uv.lock ./
# automated_actions_client is a dependency of automated_actions_cli
COPY packages/automated_actions ./packages/automated_actions
COPY packages/automated_actions_client ./packages/automated_actions_client
COPY packages/automated_actions_cli ./packages/automated_actions_cli
COPY packages/automated_actions_utils ./packages/automated_actions_utils

COPY packages/integration_tests/ ./packages/integration_tests/
RUN cd ./packages/integration_tests/ && uv sync


#
# Test image
#
FROM base AS test

COPY --from=builder /opt/app-root /opt/app-root
COPY packages/integration_tests/Makefile ./packages/integration_tests/

RUN find ${APP_ROOT} -type d -exec chmod 777 {} \;
USER 1001

RUN make -C packages/integration_tests test


#
# Production image
#
FROM base AS prod
COPY --from=builder /opt/app-root /opt/app-root

RUN find ${APP_ROOT} -type d -exec chmod 777 {} \;
USER 1001

WORKDIR ${APP_ROOT}/src/packages/integration_tests
ENTRYPOINT ["uv", "run", "pytest"]
CMD ["tests"]
