FROM registry.access.redhat.com/ubi9/python-312@sha256:aa2a3c086013ce259af562ddc64c5aa55471c42a2a8a731f185767e86a94283b AS base
COPY --from=ghcr.io/astral-sh/uv:0.7.4@sha256:9618e472e7ed9aa980719c68e51416e7ec23d85742d9ccca5c817d76ed2eb5aa /uv /bin/uv

COPY LICENSE /licenses/

ENV \
    # use venv from ubi image
    UV_PROJECT_ENVIRONMENT=$APP_ROOT \
    # disable uv cache. it doesn't make sense in a container
    UV_NO_CACHE=true


COPY packages/automated_actions_client/README.md ./
COPY packages/automated_actions_client/pyproject.toml ./
RUN uv sync --no-install-project

COPY packages/automated_actions_client/openapi_python_client_templates ./openapi_python_client_templates
COPY packages/automated_actions_client/Makefile ./
COPY packages/automated_actions_client/tests ./tests
COPY packages/automated_actions_client/automated_actions_client ./automated_actions_client
RUN uv sync

#
# Test image
#
FROM base AS test
USER root
# allow user to create cache dirs and files, e.g. .ruff_cache, .coverage, ...
RUN chown -R 1001:0 ./
USER 1001

RUN make test

#
# PyPI publish image
#
FROM test AS pypi
# Secrets are owned by root and are not readable by others :(
USER root
RUN --mount=type=secret,id=app-sre-pypi-credentials/token make -s pypi
USER 1001
