FROM registry.access.redhat.com/ubi9/python-312@sha256:c798f775119a2e9c676fcfdb14a0d24cb562790b1a4c1bb49d0966aec039c673 AS base
COPY --from=ghcr.io/astral-sh/uv:0.9.10@sha256:29bd45092ea8902c0bbb7f0a338f0494a382b1f4b18355df5be270ade679ff1d /uv /bin/uv

COPY LICENSE /licenses/

ENV \
    # use venv from ubi image
    UV_PROJECT_ENVIRONMENT=$APP_ROOT \
    # disable uv cache. it doesn't make sense in a container
    UV_NO_CACHE=true

USER root
# install the kerberos bindings to support Kerberos if the user runs the CLI via docker
RUN dnf install -y krb5-libs krb5-workstation
USER 1001

COPY pyproject.toml uv.lock ./
# automated_actions_client is a dependency of automated_actions_cli
COPY packages/automated_actions_client ./packages/automated_actions_client
COPY packages/automated_actions_cli/README.md ./packages/automated_actions_cli/
COPY packages/automated_actions_cli/pyproject.toml ./packages/automated_actions_cli/
# install just the dependencies
RUN uv sync --frozen --no-install-project

COPY packages/automated_actions_cli/Makefile ./packages/automated_actions_cli/
COPY packages/automated_actions_cli/tests ./packages/automated_actions_cli/tests
COPY packages/automated_actions_cli/automated_actions_cli ./packages/automated_actions_cli/automated_actions_cli
RUN uv sync --frozen

#
# Test image
#
FROM base AS test
USER root
# allow user to create cache dirs and files, e.g. .ruff_cache, .coverage, ...
RUN chown -R 1001:0 ./
USER 1001

RUN make -C packages/automated_actions_cli test

#
# PyPI publish image
#
FROM test AS pypi
# Secrets are owned by root and are not readable by others :(
USER root
RUN --mount=type=secret,id=app-sre-pypi-credentials/token UV_PUBLISH_TOKEN=$(cat /run/secrets/app-sre-pypi-credentials/token) make -C packages/automated_actions_cli pypi
USER 1001
