FROM registry.access.redhat.com/ubi9/python-312@sha256:7ba356eca7f476bcf9a8c51714e43353376d37e0bbd4e43ceec7b1bcc6ff9675 AS base
COPY --from=ghcr.io/astral-sh/uv:0.11.4@sha256:5164bf84e7b4e2e08ce0b4c66b4a8c996a286e6959f72ac5c6e0a3c80e8cb04a /uv /bin/uv

COPY LICENSE /licenses/

ENV \
    # unbuffered output for easier logging
    PYTHONUNBUFFERED=1 \
    # use venv from ubi image
    UV_PROJECT_ENVIRONMENT=$APP_ROOT \
    # disable uv cache. it doesn't make sense in a container
    UV_NO_CACHE=true

USER root
# install the kerberos bindings to support Kerberos if the user runs the CLI via docker
RUN dnf install -y krb5-libs krb5-workstation
USER 1001

COPY pyproject.toml uv.lock ./
# automated_actions_client is a dependency of automated_actions_cli
COPY packages/automated_actions_client ./packages/automated_actions_client
COPY packages/automated_actions_cli/README.md ./packages/automated_actions_cli/
COPY packages/automated_actions_cli/pyproject.toml ./packages/automated_actions_cli/
# install just the dependencies
RUN uv sync --frozen --no-install-project

COPY packages/automated_actions_cli/Makefile ./packages/automated_actions_cli/
COPY packages/automated_actions_cli/tests ./packages/automated_actions_cli/tests
COPY packages/automated_actions_cli/automated_actions_cli ./packages/automated_actions_cli/automated_actions_cli
RUN uv sync --frozen

#
# Test image
#
FROM base AS test
USER root
# allow user to create cache dirs and files, e.g. .ruff_cache, .coverage, ...
RUN chown -R 1001:0 ./
USER 1001

RUN make -C packages/automated_actions_cli test

#
# PyPI publish image
#
FROM test AS pypi
# Secrets are owned by root and are not readable by others :(
USER root
RUN --mount=type=secret,id=app-sre-pypi-credentials/token UV_PUBLISH_TOKEN=$(cat /run/secrets/app-sre-pypi-credentials/token) make -C packages/automated_actions_cli pypi
USER 1001
