FROM registry.access.redhat.com/ubi9/python-312@sha256:e80ff3673c95b91f0dafdbe97afb261eab8244d7fd8b47e20ffcbcfee27fb168 AS base
COPY --from=ghcr.io/astral-sh/uv:0.7.7@sha256:83285c39ee68ed64708fca1495c2d0aad084e9ac02a8910f5180b8e36bcf803a /uv /bin/uv

COPY LICENSE /licenses/

ENV \
    # use venv from ubi image
    UV_PROJECT_ENVIRONMENT=$APP_ROOT \
    # disable uv cache. it doesn't make sense in a container
    UV_NO_CACHE=true


COPY packages/automated_actions_client/README.md ./
COPY packages/automated_actions_client/pyproject.toml ./
RUN uv sync --no-install-project

COPY packages/automated_actions_client/openapi_python_client_templates ./openapi_python_client_templates
COPY packages/automated_actions_client/Makefile ./
COPY packages/automated_actions_client/tests ./tests
COPY packages/automated_actions_client/automated_actions_client ./automated_actions_client
RUN uv sync

#
# Test image
#
FROM base AS test
USER root
# allow user to create cache dirs and files, e.g. .ruff_cache, .coverage, ...
RUN chown -R 1001:0 ./
USER 1001

RUN make test

#
# PyPI publish image
#
FROM test AS pypi
# Secrets are owned by root and are not readable by others :(
USER root
RUN --mount=type=secret,id=app-sre-pypi-credentials/token make -s pypi
USER 1001
