#
# Base image with defaults for all stages
FROM registry.access.redhat.com/ubi9/python-312-minimal@sha256:d39ebb9fb88e334b1d6a38385a264c85e1f1e6770dcd8de49466346fb7c5b7d4 AS base

COPY LICENSE /licenses/

ENV APP_ROOT=/opt/app-root
ENV \
    # unbuffered output for easier logging
    PYTHONUNBUFFERED=1 \
    # use venv from ubi image
    UV_PROJECT_ENVIRONMENT=${APP_ROOT} \
    # compile bytecode for faster startup
    UV_COMPILE_BYTECODE="true" \
    # disable uv cache. it doesn't make sense in a container
    UV_NO_CACHE=true \
    BASH_ENV="${APP_ROOT}/bin/activate" \
    ENV="${APP_ROOT}/bin/activate" \
    PROMPT_COMMAND=". ${APP_ROOT}/bin/activate" \
    IS_TESTED_FLAG="/tmp/is_tested"

WORKDIR ${APP_ROOT}/src

USER 0
# Install base dependencies
RUN microdnf install -y make && microdnf clean all
USER 1001

#
# Builder image
#
FROM registry.access.redhat.com/ubi9/python-312-minimal@sha256:d39ebb9fb88e334b1d6a38385a264c85e1f1e6770dcd8de49466346fb7c5b7d4 AS builder
COPY --from=ghcr.io/astral-sh/uv:0.11.4@sha256:5164bf84e7b4e2e08ce0b4c66b4a8c996a286e6959f72ac5c6e0a3c80e8cb04a /uv /bin/uv

ENV \
    # use venv from ubi image
    UV_PROJECT_ENVIRONMENT=${APP_ROOT} \
    # compile bytecode for faster startup
    UV_COMPILE_BYTECODE="true" \
    # disable uv cache. it doesn't make sense in a container
    UV_NO_CACHE=true

# I don't want to mess with permission issues in the builder image. We use a non-root user in the final images
USER 0

# Install build dependencies
RUN microdnf install -y python3.12-devel gcc-gfortran krb5-devel && microdnf clean all

COPY pyproject.toml uv.lock ./
# automated_actions_client is a dependency of automated_actions_cli
COPY packages/automated_actions ./packages/automated_actions
COPY packages/automated_actions_client ./packages/automated_actions_client
COPY packages/automated_actions_cli ./packages/automated_actions_cli
COPY packages/automated_actions_utils ./packages/automated_actions_utils

COPY packages/integration_tests/ ./packages/integration_tests/
RUN cd ./packages/integration_tests/ && uv sync


#
# Test image
#
FROM base AS test
COPY --from=ghcr.io/astral-sh/uv:0.11.4@sha256:5164bf84e7b4e2e08ce0b4c66b4a8c996a286e6959f72ac5c6e0a3c80e8cb04a /uv /bin/uv

COPY --from=builder --chown=1001:0 /opt/app-root /opt/app-root
COPY packages/integration_tests/Makefile ./packages/integration_tests/

RUN make -C packages/integration_tests test
RUN touch ${IS_TESTED_FLAG}

#
# Production image
#
FROM base AS prod
COPY --from=builder /opt/app-root /opt/app-root
COPY --from=test ${IS_TESTED_FLAG} ${IS_TESTED_FLAG}

WORKDIR ${APP_ROOT}/src/packages/integration_tests

ENTRYPOINT ["pytest", "-p", "no:cacheprovider"]
CMD ["tests"]
