# This file is auto-generated by OpenAPI Python Client.
# Do not edit manually.

from http import HTTPStatus
from typing import Any

import httpxyz as httpx

from ... import errors
from ...client import AuthenticatedClient, Client
from ...models.action_schema_out import ActionSchemaOut
from ...types import Response


def _get_kwargs(
    cluster: str,
    namespace: str,
    cronjob: str,
) -> dict[str, Any]:
    _kwargs: dict[str, Any] = {
        "method": "post",
        "url": f"/api/v1/openshift/trigger-cronjob/{cluster}/{namespace}/{cronjob}",
    }

    return _kwargs


def _parse_response(
    *, client: AuthenticatedClient | Client, response: httpx.Response
) -> ActionSchemaOut | None:
    if response.status_code == 202:
        response_202 = ActionSchemaOut.from_dict(response.json())

        return response_202

    if client.raise_on_unexpected_status:
        raise errors.UnexpectedStatus(response.status_code, response.content)
    else:
        return None


def _build_response(
    *, client: AuthenticatedClient | Client, response: httpx.Response
) -> Response[ActionSchemaOut]:
    return Response(
        status_code=HTTPStatus(response.status_code),
        content=response.content,
        headers=response.headers,
        parsed=_parse_response(client=client, response=response),
    )


def sync_detailed(
    cluster: str,
    namespace: str,
    cronjob: str,
    *,
    client: AuthenticatedClient | Client,
) -> Response[ActionSchemaOut]:
    """Openshift Trigger Cronjob

     Run a specified OpenShift cronjob immediately.

    Args:
        cluster (str): OpenShift cluster name
        namespace (str): OpenShift namespace
        cronjob (str): OpenShift cronjob name

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[ActionSchemaOut]
    """

    kwargs = _get_kwargs(
        cluster=cluster,
        namespace=namespace,
        cronjob=cronjob,
    )

    response = client.get_httpx_client().request(
        **kwargs,
    )

    return _build_response(client=client, response=response)


def sync(
    cluster: str,
    namespace: str,
    cronjob: str,
    *,
    client: AuthenticatedClient | Client,
) -> ActionSchemaOut | None:
    """Openshift Trigger Cronjob

     Run a specified OpenShift cronjob immediately.

    Args:
        cluster (str): OpenShift cluster name
        namespace (str): OpenShift namespace
        cronjob (str): OpenShift cronjob name

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        ActionSchemaOut
    """

    return sync_detailed(
        cluster=cluster,
        namespace=namespace,
        cronjob=cronjob,
        client=client,
    ).parsed


async def asyncio_detailed(
    cluster: str,
    namespace: str,
    cronjob: str,
    *,
    client: AuthenticatedClient | Client,
) -> Response[ActionSchemaOut]:
    """Openshift Trigger Cronjob

     Run a specified OpenShift cronjob immediately.

    Args:
        cluster (str): OpenShift cluster name
        namespace (str): OpenShift namespace
        cronjob (str): OpenShift cronjob name

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[ActionSchemaOut]
    """

    kwargs = _get_kwargs(
        cluster=cluster,
        namespace=namespace,
        cronjob=cronjob,
    )

    response = await client.get_async_httpx_client().request(**kwargs)

    return _build_response(client=client, response=response)


async def asyncio(
    cluster: str,
    namespace: str,
    cronjob: str,
    *,
    client: AuthenticatedClient | Client,
) -> ActionSchemaOut | None:
    """Openshift Trigger Cronjob

     Run a specified OpenShift cronjob immediately.

    Args:
        cluster (str): OpenShift cluster name
        namespace (str): OpenShift namespace
        cronjob (str): OpenShift cronjob name

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        ActionSchemaOut
    """

    return (
        await asyncio_detailed(
            cluster=cluster,
            namespace=namespace,
            cronjob=cronjob,
            client=client,
        )
    ).parsed


from typing import Annotated

import typer

app = typer.Typer()


@app.command(
    help="""Run a specified OpenShift cronjob immediately.""",
    rich_help_panel="Actions",
)
def openshift_trigger_cronjob(
    ctx: typer.Context,
    cluster: Annotated[
        str, typer.Option(help="OpenShift cluster name", show_default=False)
    ],
    namespace: Annotated[
        str, typer.Option(help="OpenShift namespace", show_default=False)
    ],
    cronjob: Annotated[
        str, typer.Option(help="OpenShift cronjob name", show_default=False)
    ],
) -> None:
    result = sync(
        cluster=cluster, namespace=namespace, cronjob=cronjob, client=ctx.obj["client"]
    )
    if "formatter" in ctx.obj and result is not None:
        output: Any = result
        if isinstance(result, list):
            output = [
                item.to_dict() if hasattr(item, "to_dict") else item for item in result
            ]
        elif hasattr(result, "to_dict"):
            output = result.to_dict()
        ctx.obj["formatter"](output)
